functionality:
  name: "regression_1"
  namespace: "metrics"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--evaluation_data"
    info:
      label: "perturbation"
      summary: "Perturbation dataset for benchmarking."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "sm_name"
          type: "string"
          description: "The primary name for the (parent) compound (in a standardized\
            \ representation)\nas chosen by LINCS. This is provided to map the data\
            \ in this experiment to \nthe LINCS Connectivity Map data.\n"
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
        - name: "plate_name"
          type: "string"
          description: "Plate name 6 levels"
          required: true
        - name: "row"
          type: "string"
          description: "Row name on the plate"
          required: true
        - name: "well"
          type: "string"
          description: "Well name on the plate"
          required: true
        - name: "cell_count"
          type: "string"
          description: "Number of single cells pseudobulked"
          required: true
        layers:
        - name: "n_counts"
          type: "double"
          description: "Pseudobulked values using mean approach"
          required: true
        - name: "pearson"
          type: "double"
          description: "Normalized values using pearson residuals"
          required: false
        - name: "lognorm"
          type: "double"
          description: "Normalized values using shifted logarithm "
          required: false
    example:
    - "resources_test/evaluation_datasets/op_perturbation.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--prediction"
    info:
      label: "GRN"
      summary: "GRN prediction"
      file_type: "csv"
      columns:
      - name: "source"
        description: "Source of regulation"
        type: "string"
        required: true
      - name: "target"
        description: "Target of regulation"
        type: "string"
        required: true
      - name: "weight"
        description: "Weight of regulation"
        type: "float"
        required: true
    example:
    - "resources_test/grn_models/op/collectri.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--score"
    info:
      label: "Score"
      summary: "File indicating the score of a metric."
      file_type: "h5ad"
      slots:
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
        - type: "string"
          name: "metric_ids"
          description: "One or more unique metric identifiers"
          multiple: true
          required: true
        - type: "double"
          name: "metric_values"
          description: "The metric values obtained for the given prediction. Must\
            \ be of same length as 'metric_ids'."
          multiple: true
          required: true
    example:
    - "resources_test/scores/score.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--tf_all"
    info: null
    example:
    - "resources_test/prior/tf_all.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--reg_type"
    description: "name of regretion to use"
    info: null
    default:
    - "ridge"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--subsample"
    description: "number of samples randomly drawn from perturbation data"
    info: null
    default:
    - -1
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--num_workers"
    info: null
    default:
    - 4
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--method_id"
    info: null
    example:
    - "collectri"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--apply_tf"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--clip_scores"
    description: "clips the r2 scores for each gene to make them within [0, 1]"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--layer"
    info: null
    default:
    - "pearson"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--max_n_links"
    info: null
    default:
    - 50000
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--verbose"
    info: null
    default:
    - 2
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--skeleton"
    info: null
    example:
    - "resources_test/prior/skeleton.csv"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--apply_skeleton"
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--binarize"
    description: "whether to binarize the weight"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "main.py"
  - type: "file"
    path: "src/utils/util.py"
    dest: "util.py"
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources_test/"
    dest: "resources_test/"
  info:
    label: "Regression 1"
    summary: "Calculates R2 score for regression 1"
    description: "Calculates R2 score using regression approach 1.\n"
    type: "metrics"
    type_info:
      label: "Label"
      summary: "A metric to evaluate the performance of the inferred GRN"
      description: "A metric to evaluate the performance of the inferred GRN\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.4"
  target_organization: "openproblems-bio/task_grn_inference"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_grn_inference"
  setup:
  - type: "python"
    user: false
    packages:
    - "lightgbm==4.3.0"
    - "numpy==1.26.4"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      veryhighmem: "memory = 250.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      onedaytime: "time = 24.h"
      threedaystime: "time = 72.h"
      oneweektime: "time = 168.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_inference/task_grn_inference/src/metrics/regression_1/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/metrics/regression_1"
  executable: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/metrics/regression_1/regression_1"
  viash_version: "0.8.6"
  git_commit: "8b0ecf6751141e770ff1a010a26155f3d66f8073"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
