
functionality:
  name: explanatory_analysis
  info:
    label: explanatory_analysis
    summary: "Explanatory analysis of inferred GRN to provide insights about network topology and annotations"

  arguments:
    - name: --grn_model
      type: file
      required: true
      direction: input
      example: resources_test/grn_models/collectri.csv
    - name: --peak_gene_net
      type: file
      required: false
      direction: input
      example: resources_test/grn_models/peak_gene_models/figr.csv
    - name: --annot_peak_database
      type: file 
      required: false 
      direction: input
      must_exist: false
      example: resources_test/grn_benchmark/prior/annot_peak_database.csv


    - name: --stats
      type: file
      required: false
      direction: output
      example: output/stats.json
    - name: --indegee_fig
      type: file
      required: false
      direction: output
      example: output/indegee_fig.png
    - name: --outdegee_fig
      type: file
      required: false
      direction: output
      example: output/outdegee_fig.png
    - name: --weight_cdf
      type: file
      required: false
      direction: output
      example: output/weight_cdf.png
      
    
  resources:
    - type: python_script
      path: script.py
    - path: main.py
    - path: helper.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [  ]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
