
__merge__: ../../../api/comp_method.yaml


name: grn_inference_scenicplus
namespace: "workflows"
info:
  label: grn_inference_scenicplus
  summary: "Infers GRNs from multiomics data using scenicplus."
arguments:
  - name: --scplus_mdata
    type: file
    required: false
    direction: output
    description: "Main output object."
    default: "scplus_mdata.h5mu"
  - name: --qc
    type: boolean
    default: false
    description: "Whether to perform quality control."
  - name: --cell_topic
    type: file 
    required: false
    direction: output
    description: "Cell-topics prob scores"
  - name: --grn_extended
    type: file 
    required: false
    direction: output
    description: "Source-target-peak triplets"


resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
dependencies:
  - name: grn_methods/scenicplus 

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ onedaytime, veryhighmem, highcpu ]
