
name: nakatake
namespace: "process_data"
info:
  label: Process Nakatake dataset
  summary: "Porcesses Nakatake dataset to generate inference and evaluation datasets."
  
arguments:
  - name: --nakatake_raw
    type: file 
    required: true
    direction: input
  - name: --nakatake_bulk
    type: file
    required: false
    direction: output
  - name: --nakatake_test_bulk
    type: file
    required: false
    direction: output
  - name: --nakatake_train_bulk
    type: file
    required: false
    direction: output

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py


engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ numpy==1.26.4 ]

  - type: native
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
