

name: run_benchmark
namespace: "workflows"

argument_groups:
  - name: Inputs
    arguments:
      - name: --rna
        type: file
        direction: input
        required: True
      - name: --rna_all
        type: file
        direction: input
      - name: --atac
        type: file
        direction: input
      - name: --evaluation_data
        type: file
        direction: input
      - name: --evaluation_data_sc
        type: file
        direction: input
      - name: --reg_type
        type: string
        direction: input
        default: ridge
      - name: --num_workers
        type: integer
        direction: input
        required: True
      - name: --tf_all
        type: file
        required: false
        direction: input
      - name: --regulators_consensus
        type: file
        direction: input
        must_exist: false
        required: true
        example: resources_test/grn_benchmark/prior/regulators_consensus_norman.json
      - name: --ws_consensus
        type: file
        direction: input
        required: false
        example: resources_test/grn_benchmark/prior/ws_consensus_norman.csv 
      - name: --ws_distance_background
        type: file
        direction: input
        required: false
        example: resources_test/grn_benchmark/prior/ws_distance_background_norman.csv
      - name: --layer
        type: string
        required: false
        direction: input
        default: pearson
      - name: --apply_tf_methods
        type: boolean
        required: false
        direction: input
        default: true
      - name: --apply_skeleton
        type: boolean
        required: false
        direction: input
        default: false
      - name: --skeleton
        type: file
        direction: input
        required: false
        example: resources_test/grn_benchmark/prior/skeleton.csv
      

     
      
  - name: Outputs
    arguments:
      - name: "--scores"
        type: file
        required: true
        direction: output
        description: A yaml file containing the scores of each of the methods
        default: score_uns.yaml
      - name: "--method_configs"
        type: file
        required: true
        direction: output
        default: method_configs.yaml
      - name: "--metric_configs"
        type: file
        required: true
        direction: output
        default: metric_configs.yaml
      - name: "--dataset_uns"
        type: file
        required: true
        direction: output
        default: dataset_uns.yaml
      - name: "--task_info"
        type: file
        required: true
        direction: output
        default: task_info.yaml
      

  - name: Arguments
    arguments: 
      - name: "--method_ids"
        type: string
        multiple: true
        description: A list of method ids to run. If not specified, all methods will be run.
      - name: "--metric_ids"
        type: string
        multiple: true
        description: A list of metric ids to run. If not specified, all metric will be run.
  
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - type: file
    path: /_viash.yaml

dependencies:
  - name: metrics/regression_2 
  - name: metrics/regression_1
  - name: metrics/ws_distance
  - name: metrics/sem
  - name: utils/extract_uns_metadata
    repository: openproblems
  # ---- single omics
  - name: grn_methods/portia
  - name: grn_methods/grnboost
  - name: grn_methods/scenic
  - name: grn_methods/ppcor 
  - name: grn_methods/scprint 
  
  # ---- multiomics 
  - name: grn_methods/celloracle
  - name: grn_methods/scglue
  - name: grn_methods/figr
  - name: grn_methods/scenicplus
  - name: grn_methods/granie
  # ---- baselines
  - name: control_methods/pearson_corr
  - name: control_methods/negative_control
  - name: control_methods/positive_control

runners:
  - type: executable
  - type: nextflow
    config:
      script: |
        process.errorStrategy = 'ignore'
        trace {
            enabled = true
            overwrite = true
            file = "${params.publish_dir}/trace.txt"
        }

