
name: pseudobulk_rna
namespace: "stability_analysis"
info:
  label: Pseudobulk scRNA
  summary: Pseudobulk analysis of scRNA
  description: |
    We pseudobulk the scRNA data to test the sensitivity of the evaluation metrics.

arguments:
  - name: --rna
    __merge__: ../../api/file_rna_h5ad.yaml
    type: file
    direction: input
    required: true
    
  - name: --rna_pseudobulked
    __merge__: ../../api/file_rna_h5ad.yaml
    type: file
    direction: output 
  - name: --granularity
    type: double
    direction: input
    default: 1.0
  - name: --layer
    type: string
    direction: input
    default: X_norm

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [igraph, leidenalg]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midmem, midcpu ]
test_resources:
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
  - path: /resources_test/
    dest: resources_test/