__merge__: ../../../api/comp_method.yaml


name: scenic
namespace: "grn_methods"
info:
  label: scenic
  summary: "GRN inference using scenic"
  description: |
    GRN inference using Scenic pipeline.


arguments:
  - name: --rank_threshold
    type: integer
    direction: input 
    required: false
    default: 5000 
  - name: --auc_threshold
    type: double
    direction: input 
    required: false
    default: 0.05 
  - name: --nes_threshold
    type: double
    direction: input 
    required: false
    default: 3.0
    
resources:
  - type: python_script
    path: script.py
  # - path: main.py
  - path: /src/utils/util.py
    dest: util.py
    

engines:
  - type: docker
    image: aertslab/pyscenic:0.12.1
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ anndata==0.11.0 ] 

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [onedaytime, midmem, midcpu]
