__merge__: ../../../api/comp_method.yaml


name: scgpt
namespace: "grn_methods"
info:
  label: scgpt
  summary: "GRN inference using scGPT"
  description: |
    GRN inference using scGPT.
  documentation_url: https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Attention_GRN.ipynb 
arguments:
  - name: --n_bins
    type: integer
    direction: input
    default: 51
  - name: --batch_size
    type: integer
    direction: input
    default: 10
  - name: --condition
    type: string
    direction: input
    default: cell_type

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: ajpennacchio/scgpt:0.2.1
    # TODO: Try to find working installation of flash attention (flash-attn<1.0.5)
    setup:
      - type: python
        pypi:
          - gdown
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu, biggpu]
