
name: permute_grn
namespace: "stability_analysis"
info:
  label: GRN permutation
  summary: Permutation analysis for GRN stability
  description: |
    We add different intensities of permutation to the GRN to test the sensitivity of the evaluation metrics. 
    The permutations are applied to TF-gene link, direction, sign, and weight.

arguments:
  - name: --prediction
    __merge__: ../../api/file_prediction_h5ad.yaml
    type: file
    direction: input
    required: true
  - name: --prediction_n
    __merge__: ../../api/file_prediction_h5ad.yaml
    type: file
    direction: output 
  - name: --degree
    type: integer
    direction: input
    default: 20
    description: the degree of noise to add 
  - name: --noise_type
    type: string
    direction: input 
    default: net

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: []
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midmem, midcpu ]
test_resources:
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
  - path: /resources_test/
    dest: resources_test/