
name: create_test_data
namespace: "testdata"
info:
  label: create_test_data
  summary: "Subset resources to create resources_test"


arguments:
  - name: --rna
    type: file 
    required: true
    direction: input
  - name: --rna_test
    type: file 
    required: false
    direction: output

  - name: --atac
    type: file 
    required: false
    direction: input
  - name: --atac_test
    type: file 
    required: false
    direction: input

  - name: --perturbation_data
    type: file 
    required: false
    direction: input    
  - name: --perturbation_data_test
    type: file 
    required: false
    direction: output
  

  - name: --multiomics_counts
    type: file 
    required: no
    direction: input
  - name: --multiomics_counts_test
    type: file 
    required: no
    direction: output

  - name: --perturbation_counts
    type: file 
    required: no
    direction: input
  - name: --perturbation_counts_test
    type: file 
    required: no
    direction: output
      
      
resources:
  - type: python_script
    path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
  - type: native
  
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
