functionality:
  name: "batch_correction_scgen"
  namespace: "perturbation"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--perturbation_data_n"
    info:
      label: "perturbation"
      summary: "Perturbation dataset for benchmarking."
      file_type: "h5ad"
      slots:
        layers:
        - name: "n_counts"
          type: "double"
          description: "Pseudobulked values using mean approach"
          required: true
        - name: "pearson"
          type: "double"
          description: "Normalized values using pearson residuals"
          required: true
        - name: "lognorm"
          type: "double"
          description: "Normalized values using shifted logarithm "
          required: true
    example:
    - "resources_test/evaluation_datasets/op_perturbation.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--perturbation_data_bc"
    info:
      label: "perturbation"
      summary: "Perturbation dataset for benchmarking."
      file_type: "h5ad"
      slots:
        layers:
        - name: "n_counts"
          type: "double"
          description: "Pseudobulked values using mean approach"
          required: true
        - name: "pearson"
          type: "double"
          description: "Normalized values using pearson residuals"
          required: true
        - name: "lognorm"
          type: "double"
          description: "Normalized values using shifted logarithm "
          required: true
        - name: "scgen_lognorm"
          type: "double"
          description: "Batch correction using scgen on lognorm data"
          required: true
        - name: "scgen_pearson"
          type: "double"
          description: "Batch correction using scgen on pearson data"
          required: true
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--batch_key"
    info: null
    default:
    - "plate_id"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--label_key"
    info: null
    default:
    - "cell_type"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources_test/grn-benchmark"
    dest: "resources_test/grn-benchmark"
  info:
    label: "batch_correction_scgen"
    summary: "Correct batch effects using scgen"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "janursa/scgen:19-08-2024"
  target_organization: "openproblems-bio/task_grn_inference"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_grn_inference"
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      veryhighmem: "memory = 250.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      onedaytime: "time = 24.h"
      threedaystime: "time = 72.h"
      oneweektime: "time = 168.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/perturbation/batch_correction_scgen/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/task_grn_inference/task_grn_inference/target/native/perturbation/batch_correction_scgen"
  executable: "/home/runner/work/task_grn_inference/task_grn_inference/target/native/perturbation/batch_correction_scgen/batch_correction_scgen"
  viash_version: "0.8.6"
  git_commit: "fd2bfa9db6dfa9d0d4c5ddef6ae3feac7cdeb3a0"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
