__merge__: ../../../api/unit_test.yaml

functionality:
  name: process_opsca
  namespace: "preprocessing"
  info:
    label: process_opsca
    summary: "Porcesses sc counts of perturbation data to generate pseudobulked normalized data"
    description: |
      It conducts QC on sc level to remove low quality cell and genes. 
      Then, sc counts are pseudobulked and filtered for outliers compounds, samples with low quality cells, and genes with low coverage. 
      Finally, it normalized the counts data. 
    
  arguments:
    - name: --perturbation_counts
      type: file 
      required: true
      direction: input
      example: resources_test/datasets_raw/op_perturbation_counts.h5ad 
      
    - name: --pseudobulked_data
      type: file
      required: false
      direction: output

    - name: --evaluation_data
      type: file
      required: false
      direction: output

  resources:
    - type: python_script
      path: script.py


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ sctk==0.2.2]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
