functionality:
  name: multiome_matrix
  namespace: "multiomics"
  info:
    label: multiome_matrix
    summary: "Converts data to format needed for R methods."

  arguments:
    - name: --multiomics_rna
      type: file
      required: true
      direction: input
      example: resources/grn-benchmark/multiomics_rna.h5ad
    
    - name: --multiomics_atac
      type: file
      required: true
      direction: input
      example: resources/grn-benchmark/multiomics_atac.h5ad

    - name: --rna_matrix
      type: file
      required: false
      direction: output
      example: output/scRNA/X_matrix.mtx
    - name: --atac_matrix
      type: file
      required: false
      direction: output
      example: output/scATAC/X_matrix.mtx 

    - name: --rna_gene_annot
      type: file
      required: false
      direction: output
      example: output/scRNA/annotation_gene.csv

    - name: --rna_cell_annot
      type: file
      required: false
      direction: output
      example: output/scRNA/annotation_cell.csv 
   
    - name: --atac_peak_annot
      type: file
      required: false
      direction: output
      example: output/scATAC/annotation_gene.csv
      
    - name: --atac_cell_annot
      type: file
      required: false
      direction: output
      example: output/scATAC/annotation_cell.csv
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
