
name: run_permutation_analysis
namespace: "workflows"
info:
  label: Permutation analysis
  summary: "Permutes GRNs and evaluates the scores"
argument_groups:
  - name: Inputs
    arguments:
      - name: --evaluation_data
        type: file
        direction: input
      - name: --prediction
        type: file
        direction: input
        required: true
      - name: --reg_type
        type: string
        direction: input
        default: ridge
      - name: --num_workers
        type: integer
        direction: input
        required: True
      - name: --regulators_consensus
        type: file
        direction: input
        must_exist: false
        required: true
        example: resources_test/grn_benchmark/prior/regulators_consensus_norman.json
      - name: --degree
        type: integer
        required: false
        direction: input
        default: 20
      - name: --noise_type
        type: string
        required: false
        direction: input
        default: weight
      - name: --tf_all
        type: file
        required: false
        direction: input
      
      
  - name: Outputs
    arguments:
      - name: "--scores"
        type: file
        required: true
        direction: output
        default: "scores.yaml"
      - name: "--metric_configs"
        type: file
        required: true
        direction: output
        default: metric_configs.yaml
  - name: Arguments
    arguments: 
      - name: "--metric_ids"
        type: string
        multiple: true
        description: A list of metric ids to run. If not specified, all metric will be run.
  

  
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

dependencies:
  - name: metrics/regression_1
  - name: metrics/regression_2
  - name: metrics/ws_distance
  - name: stability_analysis/permute_grn
  - name: utils/extract_uns_metadata
    repository: openproblems

runners:
  - type: executable
  - type: nextflow
