

name: create_test_resources
namespace: "workflows"
info:
  label: create_test_resources
  summary: "Subsets multiomics and perturbation datasets to create test resources"

arguments:
  - name: --multiomics_rna
    type: file 
    required: true
    direction: input
    default: resources/grn-benchmark/multiomics_rna.h5ad
  - name: --multiomics_atac
    type: file 
    required: true
    direction: input
    default: resources/grn-benchmark/multiomics_atac.h5ad
  - name: --perturbation_data
    type: file 
    required: true
    direction: input
    default: resources/grn-benchmark/perturbation_data.h5ad
  
  - name: --multiomics_rna_test
    type: file 
    required: true
    direction: output
    default: resources_test/grn-benchmark/multiomics_rna.h5ad
  - name: --multiomics_atac_test
    type: file 
    required: true
    direction: output
    default: resources_test/grn-benchmark/multiomics_atac.h5ad
  - name: --perturbation_data_test
    type: file 
    required: true
    direction: output
    default: resources_test/grn-benchmark/perturbation_data.h5ad
  
  - name: --rna_rds_test
    type: file
    required: true
    direction: output
    default: resources_test/grn-benchmark/multiomics_r/rna.rds
  - name: --atac_rds_test
    type: file
    required: true
    direction: output
    default: resources_test/grn-benchmark/multiomics_r/atac.rds
  
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
dependencies:
  - name: multiomics/multiome_matrix
  - name: multiomics/format_resources_r 
  - name: testdata/create_test_data

runners:
  - type: excutable
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
