functionality:
  name: consensus_for_regression_2
  info:
    label: Consensus regression 2
    summary: Infer consensus for regression 2
    description: |
      Compute distribution of putative regulators for each gene, based on a set of inferred GRNs
  resources:
    - type: python_script
      path: script.py
  arguments:
    - name: --perturbation_data
      type: file
      direction: input
      must_exist: true
    - name: --grn_folder
      type: file
      direction: input
      must_exist: true
    - name: --grns
      type: string
    - name: --output
      type: file
      direction: output
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]