functionality:
  name: "create_test_resources"
  namespace: "workflows"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--multiomics_rna"
    info: null
    default:
    - "resources/grn-benchmark/multiomics_rna.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--multiomics_atac"
    info: null
    default:
    - "resources/grn-benchmark/multiomics_atac.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--perturbation_data"
    info: null
    default:
    - "resources/grn-benchmark/perturbation_data.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--multiomics_rna_test"
    info: null
    default:
    - "resources_test/grn-benchmark/multiomics_rna.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--multiomics_atac_test"
    info: null
    default:
    - "resources_test/grn-benchmark/multiomics_atac.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--perturbation_data_test"
    info: null
    default:
    - "resources_test/grn-benchmark/perturbation_data.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--rna_rds_test"
    info: null
    default:
    - "resources_test/grn-benchmark/multiomics_r/rna.rds"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--atac_rds_test"
    info: null
    default:
    - "resources_test/grn-benchmark/multiomics_r/atac.rds"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  info:
    label: "create_test_resources"
    summary: "Subsets multiomics and perturbation datasets to create test resources"
  status: "enabled"
  dependencies:
  - name: "multiomics/multiome_matrix"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/multiome_matrix/config.vsh.yaml"
    configInfo:
      functionalityName: "multiome_matrix"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/multiome_matrix/config.vsh.yaml"
      functionalityNamespace: "multiomics"
      output: ""
      platform: ""
      git_commit: "94c79b7c8eaeaa13bd9a9b797307fb0362b3b7d2"
      executable: "/nextflow/multiomics/multiome_matrix/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/multiomics/multiome_matrix"
  - name: "multiomics/format_resources_r"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/format_resources_r/config.vsh.yaml"
    configInfo:
      functionalityName: "format_resources_r"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/format_resources_r/config.vsh.yaml"
      functionalityNamespace: "multiomics"
      output: ""
      platform: ""
      git_commit: "94c79b7c8eaeaa13bd9a9b797307fb0362b3b7d2"
      executable: "/nextflow/multiomics/format_resources_r/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/multiomics/format_resources_r"
  - name: "testdata/create_test_data"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/test_data/config.vsh.yaml"
    configInfo:
      functionalityName: "create_test_data"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/test_data/config.vsh.yaml"
      functionalityNamespace: "testdata"
      output: ""
      platform: ""
      git_commit: "94c79b7c8eaeaa13bd9a9b797307fb0362b3b7d2"
      executable: "/nextflow/testdata/create_test_data/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/testdata/create_test_data"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      veryhighmem: "memory = 250.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      onedaytime: "time = 24.h"
      threedaystime: "time = 72.h"
      oneweektime: "time = 168.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_inference/task_grn_inference/src/workflows/create_resources_test/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/workflows/create_test_resources"
  executable: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/workflows/create_test_resources/main.nf"
  viash_version: "0.8.6"
  git_commit: "94c79b7c8eaeaa13bd9a9b797307fb0362b3b7d2"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
