import os
import sys
import tarfile
import tempfile
import zipfile

import anndata as ad
import gdown
import scgpt
import torch

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
    "input": "resources_test/.../input.h5ad",
    "output": "output.h5ad",
    "model_name": "scGPT_human",
    "model": "scGPT_human",
    "n_hvg": 3000,
}
meta = {"name": "scgpt"}
## VIASH END

# sys.path.append(meta["resources_dir"])
# from read_anndata_partial import read_anndata
# from exit_codes import exit_non_applicable