
__merge__: ../../api/comp_metric.yaml


name: metrics_all
namespace: "metrics"
info:
  label: metrics_all
  summary: Calculates all metrics for a given GRN and dataset

arguments: 
  - name: --evaluation_data
    __merge__: ../../api/file_evaluation_bulk_h5ad.yaml
    required: true
    direction: input
  - name: --evaluation_data_sc
    __merge__: ../../api/file_evaluation_sc_h5ad.yaml
    required: true
    direction: input


  - name: --reg_type
    type: string
    direction: input
    default: ridge
    description: name of regretion to use
    multiple: false

  - name: --regulators_consensus
    type: file
    direction: input
    must_exist: false
    required: true
    example: resources_test/grn_benchmark/prior/regulators_consensus_norman.json
  - name: --static_only
    direction: input
    type: boolean
    default: true
  - name: --binarize
    type: boolean 
    direction: input 
    description: whether to binarize the weight
    default: true
  - name: --ws_consensus
    type: file
    direction: input
    must_exist: false
    required: true
    example: resources_test/grn_benchmark/prior/ws_consensus_norman.csv 
  - name: --ws_distance_background
    type: file
    direction: input
    must_exist: false
    required: true
    example: resources_test/grn_benchmark/prior/ws_distance_background_norman.csv

  - name: --tf_all
    type: file
    direction: input
    required: true
    example: resources_test/grn_benchmark/prior/tf_all.csv


resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py
  - path: /src/metrics/regression_1/script.py
    dest: reg1_main.py
  - path: /src/metrics/regression_2/main.py
    dest: reg2_main.py
  - path: /src/metrics/wasserstein/main.py
    dest: ws_main.py


engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ lightgbm==4.3.0, numpy==1.26.4 ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midmem, midcpu ]