__merge__: ../../../api/comp_method.yaml

name: scglue
namespace: "grn_methods"
info:
  label: scglue
  summary: "GRN inference using scglue"
  description: |
    GRN inference using scglue. 
  documentation_url: https://scglue.readthedocs.io/
arguments:
  - name: --top_n_targets
    type: string
    required: false
    direction: input
    default: 100
  - name: --rank_threshold
    type: string
    required: false
    direction: input
    default: 1500
  - name: --nes_threshold
    type: string
    required: false
    direction: input
    default: 1.5
  - name: --extend_range
    type: integer
    required: false
    direction: input
    default: 0
    description: extending range of promotors to connect to peak
resources:
  - type: python_script
    path: script.py
  - path: main.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: janursa/scglue:19-08-2024
    # image: nvcr.io/nvidia/pytorch:24.06-py3
    # setup:
    #   - type: python
    #     packages: [ scglue==0.3.2, pyscenic==0.12.1, numpy==1.23.4, scanpy, networkx, pyarrow, cytoolz, scikit-misc, cuda-python, faiss-gpu]
    #   - type: apt
    #     packages: [bedtools]

  - type: native
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [oneweektime, midmem, highcpu, gpu]
