__merge__: ../../../api/comp_method.yaml

name: dictys
namespace: grn_methods
info:
  label: dictys
  summary: "GRN inference using dictys"
  description: |
    Infers gene regulatory networks from paired RNA-seq and ATAC-seq data using dictys.
    The workflow combines multimodal data, creates peak-to-gene linkages, and integrates 
    transcription factor binding information to predict gene regulatory relationships.
  documentation_url: https://github.com/pinellolab/dictys
arguments:
  - name: --distance
    type: integer
    default: 500000
    description: "Distance threshold for peak-to-gene assignment"
  - name: --qc
    type: boolean
    default: true
    description: "Whether to perform quality control"

resources:
  - type: python_script
    path: script.py
  - path: helper.py
  

engines:
  - type: docker
    image: agabriel/dictys:v1
    setup:
      - type: python
        pypi:
          - gdown
    # setup:   
    #   - type: python
    #     github:
    #       - openproblems-bio/core#subdirectory=packages/python/openproblems

runners:
  - type: executable
  - type: nextflow
    directives:
      label: []