__merge__: ../../api/comp_control_method.yaml

name: spearman_corr
info:
  label: Spearman correlation
  summary: "Baseline based on correlation"
  description: |
    Baseline GRN inference method using Spearman correlation.


resources:
  - type: python_script
    path: script.py

  - path: /src/utils/util.py
    dest: util.py
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [  ]
  - type: native
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
