name: "ws_distance"
namespace: "metrics"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--prediction"
    label: "GRN prediction"
    summary: "File indicating the inferred GRN."
    info:
      format:
        type: "h5ad"
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the inference method"
          required: true
        - type: "DataFrame"
          name: "prediction"
          description: "Inferred GRNs in the format of source, target, weight"
          required: true
    example:
    - "resources/grn_models/op/collectri.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--score"
    label: "score"
    summary: "File indicating the score of a metric."
    info:
      format:
        type: "h5ad"
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
        - type: "string"
          name: "metric_ids"
          description: "One or more unique metric identifiers"
          multiple: true
          required: true
        - type: "double"
          name: "metric_values"
          description: "The metric values obtained for the given prediction. Must\
            \ be of same length as 'metric_ids'."
          multiple: true
          required: true
    example:
    - "resources_test/scores/score.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--method_id"
    info: null
    example:
    - "grnboost2"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--layer"
    info: null
    default:
    - "X_norm"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--max_n_links"
    info: null
    default:
    - 50000
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--verbose"
    info: null
    default:
    - 2
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_id"
    info: null
    default:
    - "op"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--ws_consensus"
    info: null
    example:
    - "resources_test/prior/ws_consensus_adamson.csv"
    must_exist: false
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--ws_distance_background"
    info: null
    example:
    - "resources_test/prior/ws_distance_background_adamson.csv"
    must_exist: false
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--evaluation_data_sc"
    info: null
    example:
    - "resources_test/datasets_raw/adamson_sc_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
- type: "file"
  path: "util.py"
  dest: "util.py"
- type: "file"
  path: "main.py"
test_resources:
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "file"
  path: "resources_test/"
  dest: "resources_test/"
info:
  label: "ws_distance"
  summary: "Calculates Wasserstein distance for a given GRN and dataset"
  type: "metrics"
  type_info:
    label: "metrics"
    summary: "A metric to evaluate the performance of the inferred GRN"
    description: "A metric to evaluate the performance of the inferred GRN\n"
status: "enabled"
scope:
  image: "public"
  target: "public"
repositories:
- type: "github"
  name: "openproblems"
  repo: "openproblems-bio/openproblems"
  tag: "build/main"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_grn_inference"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.4"
  namespace_separator: "/"
  setup:
  - type: "apt"
    packages:
    - "procps"
    - "git"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "anndata~=0.10.0"
    - "scanpy~=1.10.0"
    - "pyyaml"
    - "requests"
    - "jsonschema"
    github:
    - "openproblems-bio/core#subdirectory=packages/python/openproblems"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "numpy==1.26.4"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/metrics/wasserstein/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/metrics/ws_distance"
  executable: "target/nextflow/metrics/ws_distance/main.nf"
  viash_version: "0.9.1"
  git_commit: "09c28006fee3c89826e9555fde5cd07e28e2a306"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
package_config:
  name: "task_grn_inference"
  version: "build_main"
  label: "GRN Inference"
  summary: "Benchmarking GRN inference methods\n"
  description: "\ngeneRNIB is a living benchmark platform for GRN inference. This\
    \ platform provides curated datasets for GRN inference and evaluation, standardized\
    \ evaluation protocols and metrics, computational infrastructure, and a dynamically\
    \ updated leaderboard to track state-of-the-art methods. It runs novel GRNs in\
    \ the cloud, offers competition scores, and stores them for future comparisons,\
    \ reflecting new developments over time.\n\nThe platform supports the integration\
    \ of new inference methods, datasets and protocols. When a new feature is added,\
    \ previously evaluated GRNs are re-assessed, and the leaderboard is updated accordingly.\
    \ The aim is to evaluate both the accuracy and completeness of inferred GRNs.\
    \ It is designed for both single-modality and multi-omics GRN inference. \n\n\
    In the current version, geneRNIB contains 11 inference methods including both\
    \ single and multi-omics, 8 evalation metrics, and five datasets (OPSCA, Nakatake,\
    \ Norman, Adamson, and Replogle). \n\nSee our publication for the details of methods.\
    \ \n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/grn/inference_datasets/"
      dest: "resources_test/inference_datasets/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/grn/evaluation_datasets/"
      dest: "resources_test/evaluation_datasets/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/grn/prior/"
      dest: "resources_test/prior/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/grn/grn_models/"
      dest: "resources_test/grn_models/"
    readme: "## Installation\n\nYou need to have Docker, Java, and Viash installed.\
      \ Follow\n[these instructions](https://openproblems.bio/documentation/fundamentals/requirements)\n\
      to install the required dependencies. \n\n## Download resources\n```bash\ngit\
      \ clone git@github.com:openproblems-bio/task_grn_inference.git\n\ncd task_grn_inference\n\
      \n# download resources \nTo interact with the framework, you should download\
      \ the resources containing necessary inferene and evaluation datasets to get\
      \ started.\n```bash\nscripts/download_resources.sh\n```\n\n## Infer a GRN \n\
      \nTo infer a GRN for a given dataset (e.g. `norman`) using simple Pearson correlation:\n\
      ```bash\nviash run src/control_methods/pearson_corr/config.vsh.yaml -- \\\n\
      \          --rna resources/inference_datasets/norman_rna.h5ad --prediction output/net.h5ad\n\
      ```\n\n```bash\n## Evaluate a GRN\nOnce got the prediction for a given dataset,\
      \ use the following code to obtain evaluation scores. \n```bash\nscripts/single_grn_evaluation.sh\
      \ output/net.h5ad norman\n```\nThis will calculate and print the scores as well\
      \ as output the scores into `output/score.h5ad`\n\n## Add a method\n\nTo add\
      \ a method to the repository, follow the instructions in the `scripts/add_a_method.sh`\
      \ script.\n"
  repositories:
  - type: "github"
    name: "openproblems"
    repo: "openproblems-bio/openproblems"
    tag: "build/main"
  viash_version: "0.9.1"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "Jalil Nourisa"
    roles:
    - "author"
    info:
      github: "janursa"
      orcid: "0000-0002-7539-4396"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Antoine Passimier"
    roles:
    - "contributor"
    info:
      github: "AntoinePassemiers"
  - name: "Marco Stock"
    roles:
    - "contributor"
    info:
      github: "stkmrc"
  - name: "Christian Arnold"
    roles:
    - "contributor"
    info:
      github: "chrarnold"
  keywords:
  - "gene regulatory network"
  - "network inference"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_grn_inference"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_grn_inference/issues"
