
name: dummy_metric
namespace: "metrics"
info:
  label: dummy_metric
  summary: Place holder
  
arguments: 
  - name: --layer
    type: string 
    direction: input 
    default: X_norm
  - name: --score
    type: file
    required: true
    direction: output

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py
      
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ lightgbm==4.3.0, numpy==1.26.4 ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]
