__merge__: ../../api/comp_method.yaml
functionality:
  name: negative_control
  namespace: control_methods
  info:
    label: Negative control
    summary: Source-target links based on random assignment
    description: |
      Randomly assigns regulatory links to tf-target links with a given tf and target list. This is to perform near random.
  arguments:
    - name: --perturbation_data
      type: file
      required: true
      direction: input
      example: resources_test/grn-benchmark/perturbation_data.h5ad
    
  resources:
    - type: python_script
      path: script.py
    - path: main.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [  ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]