__merge__: ../../api/comp_method.yaml

functionality:
  name: positive_control
  namespace: control_methods
  info:
    label: positive_control
    summary: "Baseline based on correlation"

  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/util.py
      dest: util.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        # packages: [ magic-impute ]
        packages: [  ]
  - type: native
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
