__merge__: ../../api/comp_method.yaml


name: positive_control
namespace: control_methods
info:
  label: positive_control
  summary: "Baseline based on correlation"

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        # packages: [ magic-impute ]
        packages: [  ]
  - type: native
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
