
name: opsca
namespace: "process_data"
info:
  label: Process OPSCA dataset
  summary: "Porcesses sc counts of perturbation data to generate pseudobulked normalized data. Also, it reads multiome data and generates RNA and ATAC normalized data."
  description: |
    It conducts QC on sc level to remove low quality cell and genes. Then, sc counts are pseudobulked and filtered for outliers compounds, samples with low quality cells, and genes with low coverage. 
    Finally, it normalized the counts data. 
    For multiome data, it reads the data, splits into RNA and ATAC and normalizes.
  
arguments:
  - name: --op_perturbation_raw
    type: file 
    required: true
    direction: input
    example: resources_test/datasets_raw/op_perturbation_sc_counts.h5ad 

  - name: --op_perturbation_bulk
    type: file
    required: false
    direction: output
  
  - name: --op_multiome
    type: file 
    required: true
    direction: input

  - name: --op_rna
    type: file 
    required: false
    direction: output

  - name: --op_atac
    type: file 
    required: false
    direction: output
  
  - name: --op_perturbation_bulk_test
    type: file 
    required: false
    direction: output

  - name: --op_rna_test
    type: file 
    required: false
    direction: output

  - name: --op_atac_test
    type: file 
    required: false
    direction: output



resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py
  - path: helper.py


engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ sctk==0.2.2]

  - type: native
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
