
name: reologle_k562_gwps
namespace: "process_data"
info:
  label: Process reologle_k562_gwps dataset
  summary: "Process sourced reologle_k562_gwps data to generate inference and evaluation datasets"

arguments:
  - name: --replogle_gwps
    type: file
    required: true
    direction: input
  - name: --tf_all
    type: file
    required: true
    direction: input
  - name: --replogle_test_perturbs
    type: file
    required: true
    direction: input
  - name: --replogle_gwps_test_sc
    type: file
    required: true
    direction: output
  - name: --replogle_gwps_train_sc
    type: file
    required: true
    direction: output
  - name: --replogle_gwps_train_sc_subset
    type: file
    required: true
    direction: output


resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ numpy==1.26.4 ]
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
