functionality:
  name: "scgpt"
  namespace: "grn_methods"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--rna"
    info:
      label: "multiomics rna"
      summary: "RNA expression for multiomics data."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
    example:
    - "resources_test/inference_datasets/op_rna.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--atac"
    info:
      label: "multiomics atac"
      summary: "Peak data for multiomics data."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
    example:
    - "resources_test/inference_datasets/op_atac.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--prediction"
    info:
      label: "GRN"
      summary: "GRN prediction"
      file_type: "csv"
      columns:
      - name: "source"
        description: "Source of regulation"
        type: "string"
        required: true
      - name: "target"
        description: "Target of regulation"
        type: "string"
        required: true
      - name: "weight"
        description: "Weight of regulation"
        type: "float"
        required: true
    example:
    - "resources_test/grn_models/op/collectri.csv"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--tf_all"
    info: null
    example:
    - "resources_test/prior/tf_all.csv"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--max_n_links"
    info: null
    default:
    - 50000
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--num_workers"
    info: null
    default:
    - 4
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--temp_dir"
    info: null
    default:
    - "output/temdir"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--seed"
    info: null
    default:
    - 32
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--causal"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--n_bins"
    info: null
    default:
    - 51
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--batch_size"
    info: null
    default:
    - 10
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--condition"
    info: null
    default:
    - "cell_type"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources_test/"
    dest: "resources_test/"
  info:
    label: "scgpt"
    summary: "GRN inference using scGPT"
    description: "GRN inference using scGPT.\n"
    documentation_url: "https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Attention_GRN.ipynb"
    type: "methods"
    type_info:
      label: "Method"
      summary: "A GRN inference method"
      description: "A method for inferring GRN from expression data.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "xueerchen/scgpt:0.1.7"
  target_organization: "openproblems-bio/task_grn_inference"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_grn_inference"
  setup:
  - type: "python"
    user: false
    upgrade: true
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    - "gpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      veryhighmem: "memory = 250.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      onedaytime: "time = 24.h"
      threedaystime: "time = 72.h"
      oneweektime: "time = 168.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/scgpt/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/scgpt"
  executable: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/scgpt/scgpt"
  viash_version: "0.8.6"
  git_commit: "8b0ecf6751141e770ff1a010a26155f3d66f8073"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
