
__merge__: ../../../api/comp_method.yaml


name: grn_inference_celloracle
namespace: "workflows"
info:
  label: grn_inference_celloracle
  summary: "Infers GRNs from multiomics data using celloracle."
arguments:
  - name: --base_grn
    type: file
    direction: output
    default: output/celloracle/base_grn.csv
    
  # - name: --links
  #   type: file
  #   direction: output
  #   default: output/celloracle/links.celloracle.links
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
dependencies:
  - name: grn_methods/celloracle 

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
