functionality:
  name: create_component
  namespace: common
  description: |
    Create a component Viash component.
    
    Usage:
    ```
    bin/create_component --task denoising --type method --language r --name foo
    bin/create_component --task denoising --type metric --language python --name bar
    ```
  arguments:
    - type: string
      name: --type
      description: What kind of component to create. Options are method or metric.
      default: method
      choices: [method, metric]
    - type: string
      name: --language
      description: Which scripting language to use. Options are 'python', 'r'.
      default: python
      choices: [python, r]
    - type: string
      name: --name
      example: new_comp
      description: Name of the new method, formatted in snake case.
    - type: file
      name: --output
      direction: output
      # required: true
      description: Path to the component directory. Suggested location is `src/<TASK>/<TYPE>s/<NAME>`.
      default: src/methods/${VIASH_PAR_NAME}
    - type: file
      name: --api_file
      description: |
        Which API file to use. Defaults to `src/<TASK>/api/comp_<TYPE>.yaml`.
        In tasks with different subtypes of method, this location might not exist and you might need
        to manually specify a different API file to inherit from.
      must_exist: false
      required: false
      default: src/api/comp_method.yaml
    - type: file
      name: --viash_yaml
      description: |
        Path to the project config file. Needed for knowing the relative location of a file to the project root.
      # required: true
      default: "_viash.yaml"
  resources:
    - type: python_script
      path: script.py
    - path: read_and_merge_yaml.py
platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: python
        pypi: ruamel.yaml
  - type: native
  - type: nextflow


