import anndata as ad
import pandas as pd

## VIASH START
# The following code has been auto-generated by Viash.
par = {
  'perturbation_h5ad': r'resources/grn-benchmark/perturbation.h5ad',
  'layer': r'lognorm',
  'prediction': r'resources/grn-benchmark/collectri.csv',
  'output': r'resources/grn-benchmark/score.h5ad'
}


print('Reading input files', flush=True)
perturbation_data = ad.read_h5ad(par['perturbation_h5ad'])
grn = pd.read_csv(par['prediction'])

print('Compute metrics', flush=True)
# metric_ids and metric_values can have length > 1
# but should be of equal length
uns_metric_ids = ['r2score']
uns_metric_values = [0.5]

print("Write output AnnData to file", flush=True)
output = ad.AnnData(
  uns={
    # 'dataset_id': input_prediction.uns['dataset_id'],
    # 'normalization_id': input_prediction.uns['normalization_id'],
    # 'method_id': input_prediction.uns['method_id'],
    'metric_ids': uns_metric_ids,
    'metric_values': uns_metric_values
  }
)
output.write_h5ad(par['output'], compression='gzip')
print("Completed", flush=True)
