import anndata as ad

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'rna': 'resources_test/.../rna.h5ad',
  'atac': 'resources_test/.../atac.h5ad',
  'prediction': 'prediction.h5ad',
  'tf_all': 'resources_test/.../tf_all.h5ad',
  'max_n_links': '50000',
  'num_workers': '20',
  'temp_dir': 'output/temdir',
  'layer': 'X_norm',
  'seed': '32',
  'dataset_id': 'op'
}
meta = {
  'name': 'dummy'
}
## VIASH END

print('Reading input files', flush=True)
rna = ad.read_h5ad(par['rna'])
atac = ad.read_h5ad(par['atac'])
tf_all = ad.read_h5ad(par['tf_all'])

print('Preprocess data', flush=True)
# ... preprocessing ...

print('Train model', flush=True)
# ... train model ...

print('Generate predictions', flush=True)
# ... generate predictions ...

print("Write prediction AnnData to file", flush=True)
prediction = ad.AnnData(
  
)
prediction.write_h5ad(par['prediction'], compression='gzip')
