__merge__: ../../api/comp_metric_ws.yaml

name: ws_distance
namespace: "metrics"
info:
  label: ws_distance
  summary: Calculates Wasserstein distance for a given GRN and dataset
arguments:
  - name: --ws_consensus
    type: file
    direction: input
    must_exist: false
    required: false
    example: resources_test/grn_benchmark/prior/ws_consensus_norman.csv 
  - name: --ws_distance_background
    type: file
    direction: input
    must_exist: false
    required: false
    example: resources_test/grn_benchmark/prior/ws_distance_background_norman.csv
  - name: --silent_missing_dependencies 
    type: boolean
    required: false
    direction: input
    default: true
  
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py
  - path: main.py
  
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [numpy==1.26.4 ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midmem, midcpu ]