name: op_multiome
namespace: "process_data"
info:
  label: Process OPSCA multiome
  summary: "Gets the raw counts and produces formatize scRNA and scATAC data"

arguments:
  - name: --op_multiome
    type: file 
    required: true
    direction: input

  - name: --op_rna
    type: file 
    required: false
    direction: output

  - name: --op_atac
    type: file 
    required: false
    direction: output

resources:
  - type: python_script
    path: script.py


engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
