__merge__: ../../../api/comp_method.yaml


name: figr
namespace: "grn_methods"
info:
  label: figr
  summary: "GRN inference using figr"
  description: |
    GRN inference using figr.
  documentation_url: https://buenrostrolab.github.io/FigR/articles/FigR_shareseq.html
arguments:
  - name: --cell_topic
    type: file
    example: resources_test/grn_benchmark/prior/cell_topic.csv
    required: true
    direction: input
  - name: --peak_gene
    type: file
    required: false
    direction: output
  - name: --n_topics
    type: integer 
    direction: input
    default: 48
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: janursa/figr:19-08-2024
    __merge__: /src/api/base_requirements.yaml
    # setup:
    #   - type: python
    #     packages: [ anndata ]
    #     github:
    #       - openproblems-bio/core#subdirectory=packages/python/openproblems
  - type: native
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
