__merge__: ../../../api/comp_method.yaml


name: portia
namespace: "grn_methods"
info:
  label: portia
  summary: "GRN inference using PORTIA"
  description: |
    GRN inference using PORTIA.
  documentation_url: https://github.com/AntoinePassemiers/PORTIA


resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: continuumio/anaconda3:2024.02-1
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ anndata==0.11.0, numpy==1.26.4, scipy==1.16.0, scikit-learn==1.7.1, portia-grn==0.0.21 ]
  - type: native
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, highmem, midcpu]
