__merge__: ../../../api/comp_method.yaml

name: scprint
namespace: "grn_methods"
info:
  label: scprint
  summary: "GRN inference using scPRINT"
  description: |
    GRN inference using scPRINT.
  documentation_url: https://github.com/cantinilab/scPRINT/
arguments:
  - name: --filtration
    type: string
    direction: input
    default: "none"
  - name: --num_genes
    type: integer
    direction: input
    default: 5000
  - name: --max_cells
    type: integer
    direction: input
    default: 1000
  - name: --populate_ontology
    type: boolean
    direction: input
    default: true
  - name: --download_checkpoint
    type: boolean
    direction: input
    default: true
  - name: --model_name
    type: string
    direction: input
    default: "v2-medium"
  - name: --model
    type: file
    direction: input
    default: null
  - name: --how
    type: string
    direction: input
    default: "most var across"

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/util.py
    dest: util.py

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    setup:
      - type: python
        pip:
          - scprint==2.3.5
      - type: docker
        run: lamin init --storage ./main --name main --schema bionty
      - type: docker
        run: lamin load anonymous/main
      - type: python
        script: import bionty as bt; bt.core.sync_all_sources_to_latest()
      - type: python
        script: from scdataloader.utils import populate_my_ontology; populate_my_ontology()
  - type: native
runners:
  - type: executable
   # docker_run_args: --gpus all
  - type: nextflow
    directives:
      label: [midtime, highmem, midcpu, biggpu]
